const ecoDestinations = [
  {
    id: "costa-rica",
    title: "Costa Rica",
    subtitle: "Rainforest Retreat 🌴",
    description:
      "Eco trails and wildlife observation. Guided tours, night safaris, and conservation workshops.",
    itinerary: [
      "Day 1 – San José Arrival",
      "Day 2 – Arenal Volcano Adventure",
      "Day 3 – Monteverde Cloud Forest",
      "Day 4 – Conservation Day",
      "Day 5 – Manuel Antonio National Park",
      "Day 6 – Wildlife by Water",
      "Day 7 – Farewell in San José",
    ],
    duration: "7 days",
    price: "€1,800",
    difficulty: "Moderate",
    bestTime: "December – April",
    image: "../img/eco-destinations/costa-rica.jpg",
  },
  {
    id: "iceland",
    title: "Iceland",
    subtitle: "Energy & Nature ❄️",
    description:
      "Thermal baths and visits to geothermal energy farms. Explore volcanic landscapes and relax in hot springs.",
    itinerary: [
      "Day 1 – Reykjavik Arrival",
      "Day 2 – Golden Circle Tour",
      "Day 3 – South Coast Adventure",
      "Day 4 – Geothermal Farms",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€2,200",
    difficulty: "Easy – Moderate",
    bestTime: "June – September",
    image: "../img/eco-destinations/iceland.jpg",
  },
  {
    id: "bali",
    title: "Bali",
    subtitle: "Green Harmony 🌾",
    description:
      "Yoga, creative recycling, and organic food. Participate in eco-projects and wellness activities.",
    itinerary: [
      "Day 1 – Arrival in Ubud",
      "Day 2 – Yoga & Meditation",
      "Day 3 – Eco-Projects",
      "Day 4 – Organic Farm Visit",
      "Day 5 – Beach Retreat",
      "Day 6 – Cultural Excursion",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,500",
    difficulty: "Easy",
    bestTime: "April – October",
    image: "../img/eco-destinations/bali.avif",
  },
];

const cultureDestinations = [
  {
    id: "italy",
    title: "Italy",
    subtitle: "The Taste of Tuscany 🍷",
    description:
      "Italian cooking classes with local chefs. Wine tasting tours and hands-on pasta making sessions.",
    itinerary: [
      "Day 1 – Florence Arrival",
      "Day 2 – Cooking Class with Local Chef",
      "Day 3 – Vineyard Tour in Chianti",
      "Day 4 – Siena and Tuscan Countryside",
      "Day 5 – Truffle Hunting & Departure",
    ],
    duration: "5 days",
    price: "€1,900",
    difficulty: "Easy",
    bestTime: "May – September",
    image: "../img/culture-destinations/italy.jpg",
  },
  {
    id: "japan",
    title: "Japan",
    subtitle: "Kyoto Heritage Tour 🏯",
    description:
      "Tea ceremony and historical temples. Explore ancient streets, wear kimono, and attend craft workshops.",
    itinerary: [
      "Day 1 – Arrival in Kyoto",
      "Day 2 – Temple Tour & Tea Ceremony",
      "Day 3 – Kimono Experience & Craft Workshop",
      "Day 4 – Nijo Castle & Gion District",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€2,500",
    difficulty: "Easy",
    bestTime: "March – May, October – November",
    image: "../img/culture-destinations/japan.jpg",
  },
  {
    id: "morocco",
    title: "Morocco",
    subtitle: "Colours of Marrakech 🎭",
    description:
      "Spice markets and traditional pottery workshops. Explore medinas and taste Moroccan cuisine.",
    itinerary: [
      "Day 1 – Marrakech Arrival",
      "Day 2 – Medina & Spice Market Tour",
      "Day 3 – Pottery Workshop",
      "Day 4 – Jardin Majorelle & Souks",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€1,600",
    difficulty: "Easy – Moderate",
    bestTime: "March – May, September – November",
    image: "../img/culture-destinations/morocco.jpg",
  },
];

const extremeDestinations = [
  {
    id: "argentina",
    title: "Argentina",
    subtitle: "Patagonia Trekking 🥾",
    description:
      "Icy trails and mountain camping. Trek glaciers and experience guided adventure routes.",
    itinerary: [
      "Day 1 – El Calafate Arrival",
      "Day 2 – Glacier Trekking",
      "Day 3 – Mountain Camping",
      "Day 4 – Hiking Adventure",
      "Day 5 – Scenic Lake Tour",
      "Day 6 – Free Exploration",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€3,000",
    difficulty: "Hard",
    bestTime: "November – March",
    image: "../img/extreme-destinations/argentina.jpg",
  },
  {
    id: "uae",
    title: "UAE",
    subtitle: "Desert Skydiving 🪂",
    description:
      "Skydiving over the Dubai dunes. Enjoy desert safaris and adrenaline sports.",
    itinerary: [
      "Day 1 – Dubai Arrival",
      "Day 2 – Desert Safari",
      "Day 3 – Skydiving Adventure",
      "Day 4 – Sandboarding & Relax",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€1,800",
    difficulty: "Moderate",
    bestTime: "October – April",
    image: "../img/extreme-destinations/uae.jpg",
  },
  {
    id: "nepal",
    title: "Nepal",
    subtitle: "Himalayan Challenge 🏔️",
    description:
      "Trek to Everest Base Camp. High-altitude trekking with breathtaking views of the Himalayas.",
    itinerary: [
      "Day 1 – Kathmandu Arrival",
      "Day 2 – Lukla Flight & Trek Start",
      "Day 3 – Trek to Namche Bazaar",
      "Day 4 – Acclimatization & Hiking",
      "Day 5 – Tengboche & Monasteries",
      "Day 6 – Everest Base Camp Trek",
      "Day 7 – Return to Kathmandu",
    ],
    duration: "7 days",
    price: "€3,500",
    difficulty: "Very Hard",
    bestTime: "March – May, September – November",
    image: "../img/extreme-destinations/nepal.jpg",
  },
];

const spiritualDestinations = [
  {
    id: "peru",
    title: "Peru",
    subtitle: "Inca Energy Path 🔮",
    description:
      "Spiritual trails and ancient temples in Cusco. Meditation and sacred ceremonies included.",
    itinerary: [
      "Day 1 – Cusco Arrival",
      "Day 2 – Sacred Valley Exploration",
      "Day 3 – Meditation in Ollantaytambo",
      "Day 4 – Machu Picchu Sunrise",
      "Day 5 – Local Ceremony & Reflection",
      "Day 6 – Free Day for Self-Discovery",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,200",
    difficulty: "Moderate",
    bestTime: "May – September",
    image: "../img/spiritual-destinations/peru.jpg",
  },
  {
    id: "india",
    title: "India",
    subtitle: "The Ashram Experience 🧘",
    description:
      "Meditation and spirituality in India. Yoga retreats and cultural immersion included.",
    itinerary: [
      "Day 1 – Delhi Arrival",
      "Day 2 – Travel to Rishikesh",
      "Day 3 – Yoga & Meditation Sessions",
      "Day 4 – Spiritual Talks & Ashram Life",
      "Day 5 – Local Village Visit",
      "Day 6 – Free Reflection & Yoga",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,000",
    difficulty: "Easy",
    bestTime: "October – March",
    image: "../img/spiritual-destinations/india.jpg",
  },
  {
    id: "egypt",
    title: "Egypt",
    subtitle: "The Temples of Light 🌅",
    description:
      "Visits to Luxor’s temples and desert meditation. Experience sunrise rituals and ancient wisdom.",
    itinerary: [
      "Day 1 – Luxor Arrival",
      "Day 2 – Karnak & Luxor Temples",
      "Day 3 – Valley of the Kings",
      "Day 4 – Desert Meditation",
      "Day 5 – Nile Cruise & Reflection",
      "Day 6 – Local Market & Culture",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,900",
    difficulty: "Easy – Moderate",
    bestTime: "October – April",
    image: "../img/spiritual-destinations/egypt.jpg",
  },
];

const mindfulDestinations = [
  {
    id: "switzerland",
    title: "Switzerland",
    subtitle: "Alpine Retreat 🏞️",
    description:
      "Chalet in the Alps with spa and sound therapy. Hiking and wellness workshops included.",
    itinerary: [
      "Day 1 – Zurich Arrival",
      "Day 2 – Travel to Alps Chalet",
      "Day 3 – Spa & Sound Therapy",
      "Day 4 – Hiking & Nature Walks",
      "Day 5 – Wellness Workshops",
      "Day 6 – Alpine Leisure",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,500",
    difficulty: "Easy – Moderate",
    bestTime: "June – September",
    image: "../img/mindful-destinations/switzerland.jpg",
  },
  {
    id: "thailand",
    title: "Thailand",
    subtitle: "Mindful Coast 🌊",
    description:
      "Thai massage and yoga retreats. Beach meditation and mindfulness practices included.",
    itinerary: [
      "Day 1 – Bangkok Arrival",
      "Day 2 – Travel to Coastal Retreat",
      "Day 3 – Yoga & Beach Meditation",
      "Day 4 – Thai Massage Workshop",
      "Day 5 – Local Culture Tour",
      "Day 6 – Free Mindfulness Day",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,700",
    difficulty: "Easy",
    bestTime: "November – February",
    image: "../img/mindful-destinations/thailand.jpg",
  },
  {
    id: "portugal",
    title: "Portugal",
    subtitle: "Slow Life in Alentejo 🍃",
    description:
      "Peaceful days among vineyards and rural villages. Wine tours and craft workshops included.",
    itinerary: [
      "Day 1 – Lisbon Arrival",
      "Day 2 – Travel to Alentejo",
      "Day 3 – Vineyard & Wine Tasting",
      "Day 4 – Local Village Exploration",
      "Day 5 – Craft Workshops",
      "Day 6 – Slow Life Experiences",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,400",
    difficulty: "Easy",
    bestTime: "April – October",
    image: "../img/mindful-destinations/portugal.jpg",
  },
];

const destinations = [
  // 🌿 EcoVoyage
  {
    id: "costa-rica",
    title: "Costa Rica",
    subtitle: "Rainforest Retreat 🌴",
    description:
      "Eco trails and wildlife observation. Guided tours, night safaris, and conservation workshops.",
    itinerary: [
      "Day 1 – San José Arrival",
      "Day 2 – Arenal Volcano Adventure",
      "Day 3 – Monteverde Cloud Forest",
      "Day 4 – Conservation Day",
      "Day 5 – Manuel Antonio National Park",
      "Day 6 – Wildlife by Water",
      "Day 7 – Farewell in San José",
    ],
    duration: "7 days",
    price: "€1,800",
    difficulty: "Moderate",
    bestTime: "December – April",
    image: "../img/eco-destinations/costa-rica.jpg",
  },
  {
    id: "iceland",
    title: "Iceland",
    subtitle: "Energy & Nature ❄️",
    description:
      "Thermal baths and visits to geothermal energy farms. Explore volcanic landscapes and relax in hot springs.",
    itinerary: [
      "Day 1 – Reykjavik Arrival",
      "Day 2 – Golden Circle Tour",
      "Day 3 – South Coast Adventure",
      "Day 4 – Geothermal Farms",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€2,200",
    difficulty: "Easy – Moderate",
    bestTime: "June – September",
    image: "../img/eco-destinations/iceland.jpg",
  },
  {
    id: "bali",
    title: "Bali",
    subtitle: "Green Harmony 🌾",
    description:
      "Yoga, creative recycling, and organic food. Participate in eco-projects and wellness activities.",
    itinerary: [
      "Day 1 – Arrival in Ubud",
      "Day 2 – Yoga & Meditation",
      "Day 3 – Eco-Projects",
      "Day 4 – Organic Farm Visit",
      "Day 5 – Beach Retreat",
      "Day 6 – Cultural Excursion",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,500",
    difficulty: "Easy",
    bestTime: "April – October",
    image: "../img/eco-destinations/bali.avif",
  },

  // 🎨 CultureQuest
  {
    id: "italy",
    title: "Italy",
    subtitle: "The Taste of Tuscany 🍷",
    description:
      "Italian cooking classes with local chefs. Wine tasting tours and hands-on pasta making sessions.",
    itinerary: [
      "Day 1 – Florence Arrival",
      "Day 2 – Cooking Class with Local Chef",
      "Day 3 – Vineyard Tour in Chianti",
      "Day 4 – Siena and Tuscan Countryside",
      "Day 5 – Truffle Hunting & Departure",
    ],
    duration: "5 days",
    price: "€1,900",
    difficulty: "Easy",
    bestTime: "May – September",
    image: "../img/culture-destinations/italy.jpg",
  },
  {
    id: "japan",
    title: "Japan",
    subtitle: "Kyoto Heritage Tour 🏯",
    description:
      "Tea ceremony and historical temples. Explore ancient streets, wear kimono, and attend craft workshops.",
    itinerary: [
      "Day 1 – Arrival in Kyoto",
      "Day 2 – Temple Tour & Tea Ceremony",
      "Day 3 – Kimono Experience & Craft Workshop",
      "Day 4 – Nijo Castle & Gion District",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€2,500",
    difficulty: "Easy",
    bestTime: "March – May, October – November",
    image: "../img/culture-destinations/japan.jpg",
  },
  {
    id: "morocco",
    title: "Morocco",
    subtitle: "Colours of Marrakech 🎭",
    description:
      "Spice markets and traditional pottery workshops. Explore medinas and taste Moroccan cuisine.",
    itinerary: [
      "Day 1 – Marrakech Arrival",
      "Day 2 – Medina & Spice Market Tour",
      "Day 3 – Pottery Workshop",
      "Day 4 – Jardin Majorelle & Souks",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€1,600",
    difficulty: "Easy – Moderate",
    bestTime: "March – May, September – November",
    image: "../img/culture-destinations/morocco.jpg",
  },

  // 🏔️ WildTrails
  {
    id: "argentina",
    title: "Argentina",
    subtitle: "Patagonia Trekking 🥾",
    description:
      "Icy trails and mountain camping. Trek glaciers and experience guided adventure routes.",
    itinerary: [
      "Day 1 – El Calafate Arrival",
      "Day 2 – Glacier Trekking",
      "Day 3 – Mountain Camping",
      "Day 4 – Hiking Adventure",
      "Day 5 – Scenic Lake Tour",
      "Day 6 – Free Exploration",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€3,000",
    difficulty: "Hard",
    bestTime: "November – March",
    image: "../img/extreme-destinations/argentina.jpg",
  },
  {
    id: "uae",
    title: "UAE",
    subtitle: "Desert Skydiving 🪂",
    description:
      "Skydiving over the Dubai dunes. Enjoy desert safaris and adrenaline sports.",
    itinerary: [
      "Day 1 – Dubai Arrival",
      "Day 2 – Desert Safari",
      "Day 3 – Skydiving Adventure",
      "Day 4 – Sandboarding & Relax",
      "Day 5 – Departure",
    ],
    duration: "5 days",
    price: "€1,800",
    difficulty: "Moderate",
    bestTime: "October – April",
    image: "../img/extreme-destinations/uae.jpg",
  },
  {
    id: "nepal",
    title: "Nepal",
    subtitle: "Himalayan Challenge 🏔️",
    description:
      "Trek to Everest Base Camp. High-altitude trekking with breathtaking views of the Himalayas.",
    itinerary: [
      "Day 1 – Kathmandu Arrival",
      "Day 2 – Lukla Flight & Trek Start",
      "Day 3 – Trek to Namche Bazaar",
      "Day 4 – Acclimatization & Hiking",
      "Day 5 – Tengboche & Monasteries",
      "Day 6 – Everest Base Camp Trek",
      "Day 7 – Return to Kathmandu",
    ],
    duration: "7 days",
    price: "€3,500",
    difficulty: "Very Hard",
    bestTime: "March – May, September – November",
    image: "../img/extreme-destinations/nepal.jpg",
  },

  // 🌌 MystiQuest
  {
    id: "peru",
    title: "Peru",
    subtitle: "Inca Energy Path 🔮",
    description:
      "Spiritual trails and ancient temples in Cusco. Meditation and sacred ceremonies included.",
    itinerary: [
      "Day 1 – Cusco Arrival",
      "Day 2 – Sacred Valley Exploration",
      "Day 3 – Meditation in Ollantaytambo",
      "Day 4 – Machu Picchu Sunrise",
      "Day 5 – Local Ceremony & Reflection",
      "Day 6 – Free Day for Self-Discovery",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,200",
    difficulty: "Moderate",
    bestTime: "May – September",
    image: "../img/spiritual-destinations/peru.jpg",
  },
  {
    id: "india",
    title: "India",
    subtitle: "The Ashram Experience 🧘",
    description:
      "Meditation and spirituality in India. Yoga retreats and cultural immersion included.",
    itinerary: [
      "Day 1 – Delhi Arrival",
      "Day 2 – Travel to Rishikesh",
      "Day 3 – Yoga & Meditation Sessions",
      "Day 4 – Spiritual Talks & Ashram Life",
      "Day 5 – Local Village Visit",
      "Day 6 – Free Reflection & Yoga",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,000",
    difficulty: "Easy",
    bestTime: "October – March",
    image: "../img/spiritual-destinations/india.jpg",
  },
  {
    id: "egypt",
    title: "Egypt",
    subtitle: "The Temples of Light 🌅",
    description:
      "Visits to Luxor’s temples and desert meditation. Experience sunrise rituals and ancient wisdom.",
    itinerary: [
      "Day 1 – Luxor Arrival",
      "Day 2 – Karnak & Luxor Temples",
      "Day 3 – Valley of the Kings",
      "Day 4 – Desert Meditation",
      "Day 5 – Nile Cruise & Reflection",
      "Day 6 – Local Market & Culture",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,900",
    difficulty: "Easy – Moderate",
    bestTime: "October – April",
    image: "../img/spiritual-destinations/egypt.jpg",
  },

  // 🧘 MindfulGetaway
  {
    id: "switzerland",
    title: "Switzerland",
    subtitle: "Alpine Retreat 🏞️",
    description:
      "Chalet in the Alps with spa and sound therapy. Hiking and wellness workshops included.",
    itinerary: [
      "Day 1 – Zurich Arrival",
      "Day 2 – Travel to Alps Chalet",
      "Day 3 – Spa & Sound Therapy",
      "Day 4 – Hiking & Nature Walks",
      "Day 5 – Wellness Workshops",
      "Day 6 – Alpine Leisure",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€2,500",
    difficulty: "Easy – Moderate",
    bestTime: "June – September",
    image: "../img/mindful-destinations/switzerland.jpg",
  },
  {
    id: "thailand",
    title: "Thailand",
    subtitle: "Mindful Coast 🌊",
    description:
      "Thai massage and yoga retreats. Beach meditation and mindfulness practices included.",
    itinerary: [
      "Day 1 – Bangkok Arrival",
      "Day 2 – Travel to Coastal Retreat",
      "Day 3 – Yoga & Beach Meditation",
      "Day 4 – Thai Massage Workshop",
      "Day 5 – Local Culture Tour",
      "Day 6 – Free Mindfulness Day",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,700",
    difficulty: "Easy",
    bestTime: "November – February",
    image: "../img/mindful-destinations/thailand.jpg",
  },
  {
    id: "portugal",
    title: "Portugal",
    subtitle: "Slow Life in Alentejo 🍃",
    description:
      "Peaceful days among vineyards and rural villages. Wine tours and craft workshops included.",
    itinerary: [
      "Day 1 – Lisbon Arrival",
      "Day 2 – Travel to Alentejo",
      "Day 3 – Vineyard & Wine Tasting",
      "Day 4 – Local Village Exploration",
      "Day 5 – Craft Workshops",
      "Day 6 – Slow Life Experiences",
      "Day 7 – Departure",
    ],
    duration: "7 days",
    price: "€1,400",
    difficulty: "Easy",
    bestTime: "April – October",
    image: "../img/mindful-destinations/portugal.jpg",
  },
];
